development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: dota
 pool: 5
 username: bachdx
 password: tokyo092014
 host: bdb1.cb5wgkbfnfgu.ap-northeast-1.rds.amazonaws.com
 port: 3306
