# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c99c81ac48143ee46dc1c2ae9922fe0f6c292770afe661731ea633a1bbf022c23f5d8c962cd09776001f30409705c82fbb70025ad3dbfcfd4847ead5f856ed3

test:
  secret_key_base: c47551784ba5607fb4fd0f71df9a8170a4b67a585be94d117bca5ab85538dfcbb37d040df3f96dc90a260e4b1e6d8ef1e639e7c0b9149ad1e47a91079bb4bfdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
